"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {isSupabaseConfigured} from "@/lib/supabase/config";
import {createBrowserSupabase} from "@/lib/supabase/browser";
type Project={id:string;name:string;description:string;created_at:string};type Memory={id:string;project_id:string;title:string;body:string;status:string;updated_at:string;evidence_ref:string|null};type Connection={provider:string;accountLabel:string;status:string;resourceId:string;permissionMode:string;updatedAt:string};type SupabaseProject={ref:string;name:string;organizationId:string|null;status:string|null};type GitHubInstallation={id:number;accountLogin:string;accountType:string;repositorySelection:string};type GitHubRepo={id:number;fullName:string;private:boolean;defaultBranch:string|null};type ApiError={error?:string};const configured=isSupabaseConfigured();
export default function CloudWorkspace(){
 const [authenticated,setAuthenticated]=useState<boolean|null>(null),[projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(""),[memories,setMemories]=useState<Memory[]>([]),[connections,setConnections]=useState<Connection[]>([]),[supabaseProjects,setSupabaseProjects]=useState<SupabaseProject[]>([]),[supabaseProjectRef,setSupabaseProjectRef]=useState(""),[githubInstallations,setGithubInstallations]=useState<GitHubInstallation[]>([]),[githubInstallationId,setGithubInstallationId]=useState(""),[githubRepos,setGithubRepos]=useState<GitHubRepo[]>([]),[githubRepoId,setGithubRepoId]=useState(""),[projectName,setProjectName]=useState(""),[memoryTitle,setMemoryTitle]=useState(""),[memoryBody,setMemoryBody]=useState(""),[status,setStatus]=useState(""),[busy,setBusy]=useState(false);
 const openRouter=useMemo(()=>connections.find(x=>x.provider==="openrouter"&&x.status==="ready"),[connections]),supabaseConnection=useMemo(()=>connections.find(x=>x.provider==="supabase"&&x.status==="ready"),[connections]),selectedSupabaseBinding=useMemo(()=>connections.find(x=>x.provider==="supabase"&&x.resourceId.startsWith("supabase:project:")),[connections]),githubConnection=useMemo(()=>connections.find(x=>x.provider==="github"&&x.status==="ready"),[connections]),selectedGithubBinding=useMemo(()=>connections.find(x=>x.provider==="github"&&x.resourceId.startsWith("github:repo:")),[connections]);
 const refreshProjects=useCallback(async()=>{const r=await fetch("/api/private/projects",{credentials:"same-origin",cache:"no-store"});if(r.status===401){setAuthenticated(false);setProjects([]);return}const d:ApiError&{projects?:Project[]}=await r.json();if(!r.ok)throw Error(d.error||"Cloud projects are unavailable");setProjects(d.projects||[]);setAuthenticated(true)},[]);
 const refreshMemories=useCallback(async(id:string)=>{if(!id){setMemories([]);return}const r=await fetch("/api/private/memories?projectId="+encodeURIComponent(id),{credentials:"same-origin",cache:"no-store"});const d:ApiError&{memories?:Memory[]}=await r.json();if(!r.ok)throw Error(d.error||"Cloud memories are unavailable");setMemories(d.memories||[])},[]);
 const refreshConnections=useCallback(async(id:string)=>{if(!id){setConnections([]);return}const r=await fetch("/api/private/connections/project?projectId="+encodeURIComponent(id),{credentials:"same-origin",cache:"no-store"});const d:ApiError&{connections?:Connection[]}=await r.json();if(!r.ok){setConnections([]);return}setConnections(d.connections||[])},[]);
 const refreshSupabaseProjects=useCallback(async(id:string)=>{const r=await fetch("/api/private/connect/supabase/projects?projectId="+encodeURIComponent(id),{credentials:"same-origin",cache:"no-store"});const d:ApiError&{projects?:SupabaseProject[]}=await r.json();if(!r.ok){setSupabaseProjects([]);throw Error(d.error||"Supabase projects are unavailable")}setSupabaseProjects(d.projects||[])},[]);
 const refreshGitHubInstallations=useCallback(async(id:string)=>{const r=await fetch("/api/private/connect/github/installations?projectId="+encodeURIComponent(id),{credentials:"same-origin",cache:"no-store"});const d:ApiError&{installations?:GitHubInstallation[]}=await r.json();if(!r.ok){setGithubInstallations([]);throw Error(d.error||"GitHub installations are unavailable")}setGithubInstallations(d.installations||[])},[]);
 useEffect(()=>{if(!configured)return;let active=true;fetch("/api/private/session",{credentials:"same-origin",cache:"no-store"}).then(async r=>({ok:r.ok,data:await r.json()})).then(({ok})=>{if(active){setAuthenticated(ok);if(ok)void refreshProjects().catch(()=>setStatus("Cloud workspace temporarily unavailable."))}}).catch(()=>{if(active){setAuthenticated(false);setStatus("Backend session could not be verified.")}});return()=>{active=false}},[refreshProjects]);
 useEffect(()=>{if(typeof window==="undefined")return;const p=new URLSearchParams(window.location.search),provider=p.get("connection"),result=p.get("status");if(["openrouter","supabase","github"].includes(provider||"")&&(result==="connected"||result==="error")){const name=provider==="openrouter"?"OpenRouter":provider==="supabase"?"Supabase":"GitHub";setStatus(result==="connected"?`${name} connected successfully.`:`${name} connection failed.`);p.delete("connection");p.delete("status");window.history.replaceState({},"",window.location.pathname+(p.toString()?`?${p}`:"")+window.location.hash)}},[]);
 useEffect(()=>{setSupabaseProjects([]);setSupabaseProjectRef("");setGithubInstallations([]);setGithubInstallationId("");setGithubRepos([]);setGithubRepoId("");if(authenticated&&projectId){void refreshMemories(projectId).catch(()=>setStatus("Cloud memories could not be loaded."));void refreshConnections(projectId)}else{setMemories([]);setConnections([])}},[authenticated,projectId,refreshMemories,refreshConnections]);
 useEffect(()=>{if(projectId&&supabaseConnection)void refreshSupabaseProjects(projectId).catch(e=>setStatus(e instanceof Error?e.message:"Supabase projects are unavailable"))},[projectId,supabaseConnection,refreshSupabaseProjects]);
 useEffect(()=>{if(projectId&&githubConnection)void refreshGitHubInstallations(projectId).catch(e=>setStatus(e instanceof Error?e.message:"GitHub installations are unavailable"))},[projectId,githubConnection,refreshGitHubInstallations]);
 async function submitProject(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!authenticated||busy)return;setBusy(true);try{const r=await fetch("/api/private/projects",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:projectName.trim(),description:""})}),d:ApiError&{project?:Project}=await r.json();if(!r.ok||!d.project)throw Error(d.error||"Could not create cloud project");setProjectName("");await refreshProjects();setProjectId(d.project.id);setStatus("Cloud project created.")}catch(e){setStatus(e instanceof Error?e.message:"Cloud project failed")}finally{setBusy(false)}}
 async function startProvider(provider:"openrouter"|"supabase"|"github"){if(!authenticated||!projectId||busy)return;setBusy(true);setStatus("");try{const r=await fetch(`/api/private/connect/${provider}/start`,{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId})}),d:ApiError&{authorizationUrl?:string}=await r.json();if(!r.ok||!d.authorizationUrl)throw Error(d.error||`${provider} connection could not be started`);const target=new URL(d.authorizationUrl),allowed=provider==="openrouter"?target.origin==="https://openrouter.ai":provider==="supabase"?target.origin==="https://api.supabase.com":target.origin==="https://github.com";if(!allowed)throw Error(`Unexpected ${provider} authorization destination`);window.location.assign(target.toString())}catch(e){setStatus(e instanceof Error?e.message:`${provider} connection failed`);setBusy(false)}}
 async function selectSupabaseProject(){if(!projectId||!supabaseProjectRef||busy)return;setBusy(true);try{const r=await fetch("/api/private/connect/supabase/select-project",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId,supabaseProjectRef})}),d:ApiError&{selected?:{name:string}}=await r.json();if(!r.ok||!d.selected)throw Error(d.error||"Supabase project could not be selected");await refreshConnections(projectId);setStatus(`Supabase project ${d.selected.name} connected read-only.`)}catch(e){setStatus(e instanceof Error?e.message:"Supabase project selection failed")}finally{setBusy(false)}}
 async function loadGithubRepos(value:string){setGithubInstallationId(value);setGithubRepoId("");setGithubRepos([]);if(!value||!projectId)return;try{const r=await fetch(`/api/private/connect/github/repositories?projectId=${encodeURIComponent(projectId)}&installationId=${encodeURIComponent(value)}`,{credentials:"same-origin",cache:"no-store"}),d:ApiError&{repositories?:GitHubRepo[]}=await r.json();if(!r.ok)throw Error(d.error||"GitHub repositories are unavailable");setGithubRepos(d.repositories||[])}catch(e){setStatus(e instanceof Error?e.message:"GitHub repositories are unavailable")}}
 async function selectGithubRepo(){if(!projectId||!githubInstallationId||!githubRepoId||busy)return;setBusy(true);try{const r=await fetch("/api/private/connect/github/select-repository",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId,installationId:Number(githubInstallationId),repositoryId:Number(githubRepoId)})}),d:ApiError&{selected?:{fullName:string}}=await r.json();if(!r.ok||!d.selected)throw Error(d.error||"GitHub repository could not be selected");await refreshConnections(projectId);setStatus(`GitHub repository ${d.selected.fullName} connected read-only.`)}catch(e){setStatus(e instanceof Error?e.message:"GitHub repository selection failed")}finally{setBusy(false)}}
 async function submitMemory(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!projectId||busy)return;setBusy(true);try{const r=await fetch("/api/private/memories",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId,title:memoryTitle.trim(),body:memoryBody.trim()})}),d:ApiError=await r.json();if(!r.ok)throw Error(d.error||"Could not create memory draft");setMemoryTitle("");setMemoryBody("");await refreshMemories(projectId);setStatus("Saved as a cloud draft.")}catch(e){setStatus(e instanceof Error?e.message:"Memory draft failed")}finally{setBusy(false)}}
 async function approve(m:Memory){if(busy||m.project_id!==projectId||!window.confirm("Approve this exact cloud memory revision?"))return;setBusy(true);try{const r=await fetch("/api/private/memories/approve",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId,memoryId:m.id,expectedUpdatedAt:m.updated_at})}),d:ApiError=await r.json();if(!r.ok)throw Error(d.error||"Memory could not be approved");await refreshMemories(projectId);setStatus("Approval recorded.")}catch(e){setStatus(e instanceof Error?e.message:"Approval failed")}finally{setBusy(false)}}
 async function signOut(){setBusy(true);try{const s=createBrowserSupabase(),{error}=await s.auth.signOut();if(error)throw Error();setAuthenticated(false);setProjects([]);setMemories([]);setConnections([]);setProjectId("")}catch{setStatus("Sign-out failed. Try again.")}finally{setBusy(false)}}
 if(!configured)return <section className="panel"><h2>Cloud workspace</h2><p className="muted">Not connected. Configure the dedicated UNITY backend first.</p></section>;if(authenticated===null)return <section className="panel"><h2>Cloud workspace</h2><p>Checking your session...</p></section>;if(!authenticated)return <section className="panel"><h2>Cloud workspace</h2><a href="/auth/login">Open account sign-in</a>{status&&<p>{status}</p>}</section>;
 return <div className="columns"><section className="panel"><div className="entry-head"><h2>Cloud projects</h2><button disabled={busy} onClick={()=>void signOut()}>Sign out</button></div><form onSubmit={submitProject}><label>New project<input required minLength={2} maxLength={100} value={projectName} onChange={e=>setProjectName(e.target.value)}/></label><button disabled={busy||projectName.trim().length<2}>Create cloud project</button></form><label>Selected project<select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Select a cloud project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
 <div className="controls"><button type="button" className="primary" disabled={busy||!projectId||Boolean(openRouter)} onClick={()=>void startProvider("openrouter")}>{openRouter?"OpenRouter connected":"Connect OpenRouter"}</button><small>{openRouter?"Key stored securely":"One-click authorization; key never appears in the browser."}</small></div>
 <div className="controls"><button type="button" className="primary" disabled={busy||!projectId||Boolean(supabaseConnection)} onClick={()=>void startProvider("supabase")}>{supabaseConnection?"Supabase authorized":"Connect Supabase"}</button><small>{selectedSupabaseBinding?`Bound read-only to ${selectedSupabaseBinding.resourceId.replace("supabase:project:","")}`:"Authorize, then choose the exact Supabase project."}</small></div>{supabaseConnection&&!selectedSupabaseBinding&&<div className="controls"><label>Supabase project<select value={supabaseProjectRef} onChange={e=>setSupabaseProjectRef(e.target.value)}><option value="">Select project</option>{supabaseProjects.map(p=><option key={p.ref} value={p.ref}>{p.name} ({p.ref})</option>)}</select></label><button disabled={busy||!supabaseProjectRef} onClick={()=>void selectSupabaseProject()}>Use this Supabase project</button></div>}
 <div className="controls"><button type="button" className="primary" disabled={busy||!projectId||Boolean(githubConnection)} onClick={()=>void startProvider("github")}>{githubConnection?"GitHub authorized":"Connect GitHub"}</button><small>{selectedGithubBinding?`Bound read-only to ${selectedGithubBinding.resourceId.replace("github:repo:","")}`:"Install/authorize UNITY on GitHub, then choose the exact repository."}</small></div>{githubConnection&&!selectedGithubBinding&&<div className="controls"><label>GitHub account/install<select value={githubInstallationId} onChange={e=>void loadGithubRepos(e.target.value)}><option value="">Select GitHub account</option>{githubInstallations.map(i=><option key={i.id} value={i.id}>{i.accountLogin} ({i.accountType})</option>)}</select></label>{githubInstallationId&&<label>Repository<select value={githubRepoId} onChange={e=>setGithubRepoId(e.target.value)}><option value="">Select repository</option>{githubRepos.map(r=><option key={r.id} value={r.id}>{r.fullName}{r.private?" · private":""}</option>)}</select></label>}<button disabled={busy||!githubRepoId} onClick={()=>void selectGithubRepo()}>Use this GitHub repository</button></div>}
 {connections.length>0&&<div className="model-list">{connections.map(x=><article className="entry" key={`${x.provider}:${x.resourceId}`}><strong>{x.accountLabel}</strong><br/><small>{x.provider} · {x.resourceId} · {x.permissionMode} access</small></article>)}</div>}{status&&<p role="status" className="notice">{status}</p>}</section><section className="panel"><h2>Authoritative memory drafts</h2>{!projectId?<p>Select a cloud project.</p>:<><form onSubmit={submitMemory}><label>Title<input value={memoryTitle} onChange={e=>setMemoryTitle(e.target.value)} required/></label><label>Memory draft<textarea value={memoryBody} onChange={e=>setMemoryBody(e.target.value)} required/></label><button disabled={busy}>Save cloud draft</button></form>{memories.map(m=><article className="entry" key={m.id}><strong>{m.title}</strong><p className="prewrap">{m.body}</p>{m.status==="draft"&&<button disabled={busy} onClick={()=>void approve(m)}>Review and approve</button>}</article>)}</>}</section></div>;
}
