"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
type Project={id:string;name:string};type Connection={provider:string;accountLabel:string;status:string;resourceId:string;permissionMode:string};type VercelProject={id:string;name:string;framework:string|null;updatedAt:number|null};type ApiError={error?:string};
export default function VercelConnectPanel(){
 const [projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(""),[connections,setConnections]=useState<Connection[]>([]),[vercelProjects,setVercelProjects]=useState<VercelProject[]>([]),[vercelProjectId,setVercelProjectId]=useState(""),[status,setStatus]=useState(""),[busy,setBusy]=useState(false),[authenticated,setAuthenticated]=useState<boolean|null>(null);
 const connection=useMemo(()=>connections.find(item=>item.provider==="vercel"&&item.status==="ready"),[connections]),binding=useMemo(()=>connections.find(item=>item.provider==="vercel"&&item.resourceId.startsWith("vercel:project:")),[connections]);
 const loadProjects=useCallback(async()=>{const res=await fetch("/api/private/projects",{credentials:"same-origin",cache:"no-store"});if(res.status===401){setAuthenticated(false);return}const data:ApiError&{projects?:Project[]}=await res.json();if(!res.ok)throw Error(data.error||"Cloud projects unavailable");setProjects(data.projects||[]);setAuthenticated(true)},[]);
 const loadConnections=useCallback(async(id:string)=>{if(!id){setConnections([]);return}const res=await fetch(`/api/private/connections/project?projectId=${encodeURIComponent(id)}`,{credentials:"same-origin",cache:"no-store"});const data:ApiError&{connections?:Connection[]}=await res.json();setConnections(res.ok?data.connections||[]:[])},[]);
 const loadVercelProjects=useCallback(async(id:string)=>{const res=await fetch(`/api/private/connect/vercel/projects?projectId=${encodeURIComponent(id)}`,{credentials:"same-origin",cache:"no-store"});const data:ApiError&{projects?:VercelProject[]}=await res.json();if(!res.ok){setVercelProjects([]);throw Error(data.error||"Vercel projects unavailable")}setVercelProjects(data.projects||[])},[]);
 useEffect(()=>{void loadProjects().catch(error=>setStatus(error instanceof Error?error.message:"Cloud projects unavailable"))},[loadProjects]);
 useEffect(()=>{setVercelProjects([]);setVercelProjectId("");void loadConnections(projectId)},[projectId,loadConnections]);
 useEffect(()=>{if(projectId&&connection&&!binding)void loadVercelProjects(projectId).catch(error=>setStatus(error instanceof Error?error.message:"Vercel projects unavailable"))},[projectId,connection,binding,loadVercelProjects]);
 async function connect(){
  if(!projectId||busy)return;setBusy(true);setStatus("Opening Vercel authorization...");
  try{const res=await fetch("/api/private/connect/vercel/start",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId})});const data:ApiError&{authorizationUrl?:string}=await res.json();if(!res.ok||!data.authorizationUrl)throw Error(data.error||"Vercel connection could not start");const target=new URL(data.authorizationUrl);if(target.origin!=="https://vercel.com")throw Error("Unexpected Vercel authorization destination");const popup=window.open(target.toString(),"unity-vercel-connect","popup,width=720,height=780");if(!popup){window.location.assign(target.toString());return}
   let checks=0;const timer=window.setInterval(async()=>{checks++;await loadConnections(projectId);const r=await fetch(`/api/private/connections/project?projectId=${encodeURIComponent(projectId)}`,{credentials:"same-origin",cache:"no-store"});const d:ApiError&{connections?:Connection[]}=await r.json();if(r.ok&&(d.connections||[]).some(item=>item.provider==="vercel"&&item.status==="ready")){window.clearInterval(timer);setConnections(d.connections||[]);setStatus("Vercel authorized. Choose the exact Vercel project below.");setBusy(false);try{popup.close()}catch{};return}if(checks>=60||popup.closed){window.clearInterval(timer);setBusy(false);if(checks>=60)setStatus("Vercel authorization is taking longer than expected. You can retry safely.")}},1500);
  }catch(error){setStatus(error instanceof Error?error.message:"Vercel connection failed");setBusy(false)}
 }
 async function selectProject(){if(!projectId||!vercelProjectId||busy)return;setBusy(true);setStatus("");try{const res=await fetch("/api/private/connect/vercel/select-project",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId,vercelProjectId})});const data:ApiError&{selected?:{name:string}}=await res.json();if(!res.ok||!data.selected)throw Error(data.error||"Vercel project could not be selected");await loadConnections(projectId);setStatus(`Vercel project ${data.selected.name} connected read-only.`)}catch(error){setStatus(error instanceof Error?error.message:"Vercel project selection failed")}finally{setBusy(false)}}
 return <section className="panel" aria-label="Vercel account connection"><div className="entry-head"><h2>Vercel connection</h2><span className="pill">READ-ONLY FIRST</span></div><p className="muted">Connect the Vercel account/team for one exact UNITY cloud project, then choose the Vercel project it is allowed to read. No deployment permission is granted here.</p>{authenticated===false?<p><a href="/auth/login">Sign in to the UNITY cloud workspace first</a></p>:<><label>UNITY cloud project<select value={projectId} onChange={event=>setProjectId(event.target.value)}><option value="">Select a cloud project</option>{projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label><div className="controls"><button className="primary" disabled={busy||!projectId||Boolean(connection)} onClick={()=>void connect()}>{connection?"Vercel authorized":busy?"Please wait...":"Connect Vercel"}</button><small>{binding?`Bound read-only to ${binding.resourceId.replace("vercel:project:","")}`:"Vercel handles the login/approval. UNITY stores the returned token only in the secure vault."}</small></div>{connection&&!binding&&<div className="controls"><label>Vercel project<select value={vercelProjectId} onChange={event=>setVercelProjectId(event.target.value)}><option value="">Select Vercel project</option>{vercelProjects.map(project=><option key={project.id} value={project.id}>{project.name}{project.framework?` · ${project.framework}`:""}</option>)}</select></label><button disabled={busy||!vercelProjectId} onClick={()=>void selectProject()}>Use this Vercel project</button></div>}</>}{status&&<p role="status" className="notice">{status}</p>}</section>;
}
