import {NextResponse} from "next/server";
import {getVerifiedUser} from "@/lib/supabase/server";import {createSupabaseAdmin,isSupabaseAdminConfigured} from "@/lib/supabase/admin";import {isSupabaseConfigured} from "@/lib/supabase/config";
import {requireInfisicalBootstrap,isInfisicalConfigured} from "@/lib/security/infisical-config";import {createInfisicalLocation,createInfisicalLocationRegistry,createInfisicalVault} from "@/lib/security/infisical-vault.mjs";
import {listGitHubUserInstallations,listGitHubUserInstallationRepositories} from "@/lib/infrastructure/github-install-auth.mjs";
export const dynamic="force-dynamic";const headers={"Cache-Control":"private, no-store"};const UUID=/^[0-9a-f-]{36}$/i;
export async function GET(request:Request){
 if(!isSupabaseConfigured()||!isSupabaseAdminConfigured()||!isInfisicalConfigured())return NextResponse.json({error:"Secure GitHub connection backend is not configured"},{status:503,headers});
 const url=new URL(request.url),projectId=url.searchParams.get("projectId")||"",installationId=Number(url.searchParams.get("installationId"));if(!UUID.test(projectId)||!Number.isSafeInteger(installationId)||installationId<=0)return NextResponse.json({error:"Invalid GitHub repository request"},{status:400,headers});
 try{
  const {user}=await getVerifiedUser();if(!user)return NextResponse.json({error:"Authentication required"},{status:401,headers});const admin=createSupabaseAdmin();const {data:project}=await admin.from("projects").select("id").eq("id",projectId).eq("owner_id",user.id).maybeSingle();if(!project)return NextResponse.json({error:"Project not found"},{status:404,headers});
  const {data:account}=await admin.from("account_connections").select("credential_reference,status").eq("owner_id",user.id).eq("provider","github").eq("connection_key",`github:${projectId}`).maybeSingle();const expected=`secret:github/${projectId}/oauth`;if(!account||account.status!=="ready"||account.credential_reference!==expected)return NextResponse.json({error:"Connect GitHub first"},{status:409,headers});
  const b=requireInfisicalBootstrap(),registry=createInfisicalLocationRegistry([createInfisicalLocation({secretRef:expected,secretName:"GITHUB_USER_OAUTH_BUNDLE",projectId:b.projectId,environment:b.environment,secretPath:`${b.secretPath.replace(/\/$/,"")}/${projectId.toLowerCase()}`})]);const vault=createInfisicalVault({locations:registry,getBootstrapCredentials:async()=>({clientId:b.clientId,clientSecret:b.clientSecret})});
  const repositories=await vault.useSecret(expected,async (raw:string)=>{const bundle=JSON.parse(raw);if(!bundle?.accessToken||bundle.version!==1)throw Error("invalid");if(bundle.expiresAt&&Date.parse(bundle.expiresAt)<=Date.now())throw Error("expired");const installs=await listGitHubUserInstallations({token:bundle.accessToken});if(!installs.some(item=>item.id===installationId))throw Error("unauthorized");return listGitHubUserInstallationRepositories({token:bundle.accessToken,installationId})});
  return NextResponse.json({repositories},{headers});
 }catch(error){const expired=error instanceof Error&&error.message==="expired";return NextResponse.json({error:expired?"GitHub authorization expired. Reconnect GitHub.":"GitHub repositories are unavailable"},{status:expired?409:503,headers})}
}
