import {NextResponse} from "next/server";import {z} from "zod";import {getVerifiedUser} from "@/lib/supabase/server";import {createSupabaseAdmin,isSupabaseAdminConfigured} from "@/lib/supabase/admin";import {isSupabaseConfigured} from "@/lib/supabase/config";
import {requireInfisicalBootstrap,isInfisicalConfigured} from "@/lib/security/infisical-config";import {createInfisicalLocation,createInfisicalLocationRegistry,createInfisicalVault} from "@/lib/security/infisical-vault.mjs";import {checkWriteOrigin} from "@/lib/security/origin.mjs";import {readBoundedJson} from "@/lib/security/bounded-body.mjs";import {listVercelProjects} from "@/lib/infrastructure/vercel-integration-auth.mjs";
export const dynamic="force-dynamic";const headers={"Cache-Control":"private, no-store"};const schema=z.object({projectId:z.string().uuid(),vercelProjectId:z.string().regex(/^[A-Za-z0-9_-]{4,200}$/)}).strict();type VercelBundle={version:number;accessToken:string;teamId:string|null};type VercelProject={id:string;name:string;framework:string|null;updatedAt:number|null};
export async function POST(request:Request){
 if(!isSupabaseConfigured()||!isSupabaseAdminConfigured()||!isInfisicalConfigured())return NextResponse.json({error:"Secure Vercel connection backend is not configured"},{status:503,headers});if(!checkWriteOrigin(request.headers.get("origin"),process.env.UNITY_APP_ORIGIN).allowed)return NextResponse.json({error:"Untrusted request origin"},{status:403,headers});let payload:unknown;try{payload=await readBoundedJson(request,{maxBytes:1200})}catch{return NextResponse.json({error:"Invalid request body"},{status:400,headers})}const parsed=schema.safeParse(payload);if(!parsed.success)return NextResponse.json({error:"Invalid Vercel project selection"},{status:400,headers});
 try{
  const {user}=await getVerifiedUser();if(!user)return NextResponse.json({error:"Authentication required"},{status:401,headers});const admin=createSupabaseAdmin();const {data:project}=await admin.from("projects").select("id").eq("id",parsed.data.projectId).eq("owner_id",user.id).maybeSingle();if(!project)return NextResponse.json({error:"Project not found"},{status:404,headers});
  const {data:account}=await admin.from("account_connections").select("id,credential_reference,status").eq("owner_id",user.id).eq("provider","vercel").eq("connection_key",`vercel:${parsed.data.projectId}`).maybeSingle();const expected=`secret:vercel/${parsed.data.projectId}/oauth`;if(!account||account.status!=="ready"||account.credential_reference!==expected)return NextResponse.json({error:"Connect Vercel first"},{status:409,headers});
  const b=requireInfisicalBootstrap(),registry=createInfisicalLocationRegistry([createInfisicalLocation({secretRef:expected,secretName:"VERCEL_OAUTH_BUNDLE",projectId:b.projectId,environment:b.environment,secretPath:`${b.secretPath.replace(/\/$/,"")}/${parsed.data.projectId.toLowerCase()}`})]),vault=createInfisicalVault({locations:registry,getBootstrapCredentials:async()=>({clientId:b.clientId,clientSecret:b.clientSecret})});
  const chosen=await vault.useSecret(expected,async (raw:string)=>{const bundle=JSON.parse(raw) as VercelBundle;if(bundle?.version!==1||typeof bundle.accessToken!=="string")throw Error("invalid");const projects=await listVercelProjects({accessToken:bundle.accessToken,teamId:typeof bundle.teamId==="string"?bundle.teamId:null}) as VercelProject[];const match=projects.find((item:VercelProject)=>item.id===parsed.data.vercelProjectId);if(!match)throw Error("unauthorized");return match}) as VercelProject;
  const {data:bindings,error:readError}=await admin.from("project_account_bindings").select("id,resource_id").eq("project_id",parsed.data.projectId).eq("account_connection_id",account.id).limit(20);if(readError)return NextResponse.json({error:"Connection storage unavailable"},{status:503,headers});const existing=(bindings??[]).find((item:{id:string;resource_id:string})=>item.resource_id==="vercel:account"||item.resource_id.startsWith("vercel:project:"));const resourceId=`vercel:project:${chosen.id}`;let writeError;
  if(existing)({error:writeError}=await admin.from("project_account_bindings").update({resource_id:resourceId,permission_mode:"read",updated_at:new Date().toISOString()}).eq("id",existing.id));else ({error:writeError}=await admin.from("project_account_bindings").insert({project_id:parsed.data.projectId,account_connection_id:account.id,resource_id:resourceId,permission_mode:"read"}));if(writeError)return NextResponse.json({error:"Vercel project binding could not be saved"},{status:503,headers});
  return NextResponse.json({selected:{id:chosen.id,name:chosen.name,framework:chosen.framework},permissionMode:"read"},{headers});
 }catch{return NextResponse.json({error:"Vercel project selection failed"},{status:503,headers})}
}
